version: '3.9'

services:
  webapp:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - frontend

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  frontend:
  backend:

